version: '3.8'
services:
  db:
    image: postgres
    container_name: localdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
  app:
    container_name: app
    build: .
#    image: i_want_to_be_logged_in_to_the_internship-app
    restart: always
    ports:
      - "8888:8080"
    environment:
      JWT_AUTH_SECRET: alamakota
      JWT_LOGIN_EXPIRATION_SEC: 3600
      JWT_EMAIL_SECRET: alamapsa
      JWT_EMAIL_EXPIRATION_SEC: 300
      POSTGRES_URL: jdbc:postgresql://localdb:5432/postgres
      POSTGRES_USER: user
      POSTGRES_PASS: pass123
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      #in google account your must enabling two-step login and generate application password
      EMAIL_PASS: your own pass
