version: '3.8'
services:
  db:
    image: postgres
    container_name: localdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
  app:
    container_name: app
    build: .
#    image: i_want_to_be_logged_in_to_the_internship-app
    restart: always
    ports:
      - "8888:8080"