version: '3.8'
services:
  db:
    image: postgres
    container_name: localdb
    restart: always
    ports:
      - "5533:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: e@e.com
#      PGADMIN_DEFAULT_PASSWORD: admin
  email:
    image: grafana/smtprelay
    environment:
      - SMTP_LISTEN=:25
      - SMTP_USERNAME=some_not_re@l_user
      - SMTP_PASSWORD=p@ssword
    ports:
      - "25:25"
    container_name: email