auth:
  jwt:
    auth:
      expirationSeconds: 3600
#      secret: ${JWT_SECRET}
      secret: default
      issuer: my-backend

    email:
      expirationSeconds: 300
      secret: default
      issuer: email-sender

spring:
  datasource:
    url: jdbc:postgresql://localdb:5432/postgres
    username: user
    password: pass123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: majorapps09@gmail.com
    password: "otip yixm cfac ieyb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true