auth:
  jwt:
    auth:
      expirationSeconds: ${JWT_LOGIN_EXPIRATION_SEC}
      secret: ${JWT_AUTH_SECRET}
      issuer: my-backend

    email:
      expirationSeconds: ${JWT_EMAIL_EXPIRATION_SEC}
      secret: ${JWT_EMAIL_SECRET}
      issuer: email-sender

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true